name: Update Trading Score

on:
  schedule:
    - cron: '0 * * * *'  # Spustí se každou hodinu
  workflow_dispatch:  # Umožňuje manuální spuštění

jobs:
  update-score:
    runs-on: ubuntu-22.04  # nebo ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver  # Přepíše stávající symlink, pokud existuje
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome  # Přepíše stávající symlink, pokud existuje

      - name: Run the script
        env:
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
