name: Python Selenium Test

# Tento workflow se spustí při push nebo pull requestu na branch "main"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repozitáře
    - uses: actions/checkout@v3

    # Nastavení Python verze
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Instalace závislostí a potřebných nástrojů (Chrome a chromedriver)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver

    # Spuštění tvého Python skriptu
    - name: Run script
      run: python main.py
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
